name: Release

on:
  push:
    branches: ["!*"]
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK & mill
      uses: coursier/setup-action@v1
      with:
        jvm: "adopt:8"
        apps: mill

    - name: Set up GPG
      run: |
        echo $PGP_SECRET | base64 --decode | gpg --import --no-tty --batch --yes
      env:
        PGP_SECRET: ${{ secrets.PGP_SECRET }}

    - name: Run tests
      run: |
        ./mill __.test

    - name: Publish release
      run: |
        ./mill mill.scalalib.PublishModule/publishAll \
          --publishArtifacts __.publishArtifacts \
          --sonatypeCreds ${{ secrets.SONATYPE_USERNAME }}:${{secrets.SONATYPE_PASSWORD }} \
          --gpgArgs '--passphrase=${{ secrets.PGP_PASSPHRASE }},--no-tty,--pinentry-mode,loopback,--batch,--yes,-a,-b' \
          --signed true \
          --release true